name: flutter_web3_games
description: Iranian eSport Community

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.3'

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.0-beta.2
  get: ^4.6.5
  dio: ^4.0.4
  http_interceptor: ^1.0.2
  animations: ^2.0.3
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.12
  flutter_gen_runner: ^4.1.6
  easy_localization: ^3.0.0
  bubble_tab_indicator: ^0.1.6
  flutter_easyloading: ^3.0.5
  bitsdojo_window: ^0.1.2
  confetti: ^0.7.0
  flutter_svg: ^1.1.0
  custom_pop_up_menu: ^1.2.4
  animated_background:
  flutter_staggered_animations: ^1.0.0
  animated_text_kit: ^4.2.2
  qlevar_router: ^1.5.9

  #  window_size:
  #    git:
  #      url: https://github.com/google/flutter-desktop-embedding.git
  #      path: plugins/window_size


  url_launcher: ^6.0.12
  qr_flutter: ^4.0.0
  #  web3dart:
  #  dart_web3:
  #  flutter_web3:
#  walletconnect_dart: ^0.0.3
#  flutter_web3:

  # web3dart
  build: ^2.0.0
  build_config: ^1.0.0
  dart_style: ^2.0.0
  code_builder: ^4.0.0
  path: ^1.8.0
  built_collection: ^5.0.0
  pointycastle: ^3.4.0
  convert: ^3.0.0
  js: ^0.6.3
  uuid: ^3.0.1
  typed_data: ^1.1.6
  stream_channel: ^2.0.0
  stream_transform: ^2.0.0
  json_rpc_2: ^3.0.0

  #walletconnect
  web_socket_channel: ^2.1.0
  cryptography: ^2.0.5
  json_annotation: ^4.4.0
  stack_trace: ^1.10.0

  #flutter map
  async: ^2.8.2
  collection: ^1.15.0
  http: ^0.13.3
  latlong2: ^0.8.0
  meta: ^1.3.0
  polylabel: ^1.0.1
  positioned_tap_detector_2: ^1.0.4
  proj4dart: ^2.0.0
  tuple: ^2.0.0
  vector_math: ^2.1.0
  location: ^4.4.0


#  flutter_ipfs: ^0.0.2
#  ipfs_client_flutter: ^1.0.7
#  https://github:com/hackyguru/IPFS-Flutter:



dependency_overrides:
  async: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.2
  pedantic: ^1.11.0
  build_runner: ^2.0.3
  build_test: ^2.1.0
  test: ^1.9.0
  coverage: ^1.1.0
  flutter_lints: ^2.0.0



flutter_gen:
  output: lib/core/gen/ # Optional (default: fluttermap/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  fonts:
    - family: anjoman
      fonts:
        - asset: assets/fonts/anjoman_regular.ttf
        - asset: assets/fonts/anjoman_bold.ttf
    - family: ubuntu
      fonts:
        - asset: assets/fonts/ubuntu_mono_regular.ttf
  uses-material-design: true
  assets:
    - assets/images/
    - assets/languages/
    - assets/fonts/

#    fonts:
#      - family: Raleway
#        fonts:
#          - asset: assets/fonts/Raleway-Regular.ttf
#          - asset: assets/fonts/Raleway-Italic.ttf
#            style: italic
